"""fixes

Revision ID: 60aa0618e194
Revises: 38a4813ec7ae
Create Date: 2023-10-04 11:26:14.042929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60aa0618e194'
down_revision = '38a4813ec7ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('prod_category', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'prod_category')
    # ### end Alembic commands ###
