"""autogen pandu

Revision ID: 896729d3ae95
Revises: 3d216c2c435a
Create Date: 2023-07-23 12:13:11.574580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896729d3ae95'
down_revision = '3d216c2c435a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
