"""product total cost

Revision ID: e3e55fe940b5
Revises: 60aa0618e194
Create Date: 2023-10-05 08:36:10.085525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e55fe940b5'
down_revision = '60aa0618e194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('prod_total_cost', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'prod_total_cost')
    # ### end Alembic commands ###
